"""Edit user_uid name

Revision ID: b514627691ff
Revises: d1b0175cc1c0
Create Date: 2026-08-28 02:49:18.328276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b514627691ff'
down_revision: Union[str, Sequence[str], None] = 'd1b0175cc1c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('user_uid', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('books_useR_uid_fkey'), 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'users', ['user_uid'], ['uid'])
    op.drop_column('books', 'useR_uid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('useR_uid', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key(op.f('books_useR_uid_fkey'), 'books', 'users', ['useR_uid'], ['uid'])
    op.drop_column('books', 'user_uid')
    # ### end Alembic commands ###
