"""Realate users to books

Revision ID: d1b0175cc1c0
Revises: 9a4e352390b8
Create Date: 2026-08-28 02:42:50.394910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd1b0175cc1c0'
down_revision: Union[str, Sequence[str], None] = '9a4e352390b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('useR_uid', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'books', 'users', ['useR_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'useR_uid')
    # ### end Alembic commands ###
